### ISSUE TITLE
Support additional Amazon S3 Headers

### ISSUE THREAD

**Issue by kev5873** [zacharygolba/stratosphere#1]
There is a list of supported headers in this documentation, it would be nice to have them supported.
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html

Specifically looking at the ACL Specific ones right now, (x-amz-acl)

**Comment by kev5873** [comment]
I've created a pull request #2 that addresses this.

**Comment by papa-zakari** [comment]
Awesome!
